### ISSUE TITLE
Add function signature converter

### ISSUE THREAD

**Issue by akegaviar** [chainstacklabs/evm-knife#9]
Similar to event signature but it's Keccak256 and then then first 4 bytes.

example https://piyolab.github.io/playground/ethereum/getEncodedFunctionSignature/

public db example https://www.4byte.directory/

**Comment by soos3d** [comment]
Do you mean converting the function signature back to the function name?

**Comment by akegaviar** [comment]
It's already done, my bad. Just used it. Awesome tool!
